# Generated by Django 5.2.4 on 2025-07-20 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0002_residentprofile_delete_resident'),
    ]

    operations = [
        migrations.RenameField(
            model_name='residentprofile',
            old_name='flat_number',
            new_name='villa_number',
        ),
    ]
