# Generated by Django 5.2.4 on 2025-07-28 17:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0005_alter_maintenancepayment_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentprofile',
            name='registration_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
