# Generated by Django 5.2.4 on 2025-07-29 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0006_residentprofile_registration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancepayment',
            name='due',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
