# Generated by Django 5.2.4 on 2025-07-29 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0007_maintenancepayment_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancepayment',
            name='year',
            field=models.IntegerField(default=2025),
        ),
    ]
