# Generated by Django 5.2.4 on 2025-07-30 06:39

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0008_maintenancepayment_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positive amount (₹). Direction is set by entry_type.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('month', models.CharField(blank=True, choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=20, null=True)),
                ('year', models.PositiveSmallIntegerField(choices=[(2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029), (2030, 2030)], default=2025)),
                ('category', models.CharField(blank=True, help_text='e.g., maintenance, donation, security, utilities, repairs', max_length=50, null=True)),
                ('payment_method', models.CharField(blank=True, help_text='e.g., UPI, Cash, Card, Bank, Cheque', max_length=20, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='residents.residentprofile')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['date'], name='residents_l_date_888cc6_idx'), models.Index(fields=['entry_type'], name='residents_l_entry_t_454161_idx'), models.Index(fields=['year', 'month'], name='residents_l_year_5b38fd_idx'), models.Index(fields=['category'], name='residents_l_categor_4aac19_idx')],
            },
        ),
    ]
