# Generated by Django 5.2.4 on 2025-09-08 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0009_ledgerentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ledgerentry',
            options={'ordering': ['-date', '-id'], 'verbose_name': 'Ledger entry', 'verbose_name_plural': 'Ledger entries'},
        ),
        migrations.AlterField(
            model_name='residentprofile',
            name='villa_number',
            field=models.IntegerField(unique=True),
        ),
    ]
